<a href="https://colab.research.google.com/github/chiragguptx/data-science/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[NUMPY]
'numerical python'
consists of multi dimensional arrays ,objects ,collection of routines
vector/ matrix

to import numpy

In [1]:
import numpy as np

one dimensional array

In [3]:
prime_array=np.array([2,3,5,7,99])
print(prime_array)
print(type(prime_array))


[ 2  3  5  7 99]
<class 'numpy.ndarray'>


two dimensional array

In [6]:
newarray=np.array([[2,3],[7,99]])
print(newarray)

[[ 2  3]
 [ 7 99]]


three dimensional array

In [9]:
threed_array=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(threed_array)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
print(threed_array.shape)

(2, 2, 2)


[ARRAY INSPECTION]

ndarray.shape-- returns tuple consisting of array dimensions

In [11]:
new_array=np.array([[2,3,4],[4,5,6]])
print(new_array.shape)

(2, 3)


2) ndarrayy.ndim-- returns number of array dimension

In [12]:
array_of_interger=np.array([0,1,2,3,4,5,6,7,8,9])
print(array_of_interger.ndim)

1


3) ndarray.size-- returns total number of elements in array

In [13]:
array_of_interger=np.array([0,1,2,3,4,5,6,7,8,9])
print(array_of_interger.size)

10


4) ndarray.dtype-- returns datatype of the array

In [16]:
array_of_interger=np.array([0,1,2,3,4,5,6,7,8,9])
print(array_of_interger.dtype)

int64


5) ndarray.astype-- change the datatype of array

In [18]:
new=np.array([2,3,4])
new_arr=new.astype('float64')
print(new_arr)
print(new_arr.dtype)

[2. 3. 4.]
float64
