<a href="https://colab.research.google.com/github/chiragguptx/data-science/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[NUMPY]
'numerical python'
consists of multi dimensional arrays ,objects ,collection of routines
vector/ matrix

to import numpy

In [1]:
import numpy as np

one dimensional array

In [3]:
prime_array=np.array([2,3,5,7,99])
print(prime_array)
print(type(prime_array))


[ 2  3  5  7 99]
<class 'numpy.ndarray'>


two dimensional array

In [6]:
newarray=np.array([[2,3],[7,99]])
print(newarray)

[[ 2  3]
 [ 7 99]]


three dimensional array

In [9]:
threed_array=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(threed_array)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
print(threed_array.shape)

(2, 2, 2)
